<?php
$ROOT = (!isset($ROOT)) ? "../../../../" : $ROOT;
require_once($ROOT . "modulos/suscriptores/librerias/Configuracion.cnf.php");

/** Variables **/
$cadenas = new Cadenas();
$fechas = new Fechas();
$paises = new Paises();
$regiones = new Regiones();
$ciudades = new Ciudades();
$sectores = new Sectores();
$suscriptores=new Suscriptores();
$validaciones = new Validaciones();
$componentes=new Componentes();
$estratos=new Estratos();
$tuberias=new Tuberias();
/** Valores **/

$valores['solicitud'] = $solicitud['solicitud'];
$valores['suscriptor']=$suscriptores->disponible('normal');
$valores['documento']=$validaciones->recibir("_documento");
$valores['identificacion']=$validaciones->recibir("_identificacion");
$valores['nombres']=$validaciones->recibir("_nombres");
$valores['apellidos']=$validaciones->recibir("_apellidos");
$valores['direccion']=$validaciones->recibir("_direccion");
$valores['referencia']=$validaciones->recibir("_referencia");
$valores['estrato']=$validaciones->recibir("_estrato");
$valores['predial']=$validaciones->recibir("_predial");
$valores['latitud']=$validaciones->recibir("_latitud");
$valores['longitud']=$validaciones->recibir("_longitud");
$valores['correo']=$validaciones->recibir("_correo");
$valores['telefonos']=$validaciones->recibir("_telefonos");
$valores['creado']=$fechas->hoy();
$valores['actualizado']=$validaciones->recibir("_actualizado");
$valores['creador']=$validaciones->recibir("_creador");
$valores['actualizador']=$validaciones->recibir("_actualizador");
$valores['diametro']=$validaciones->recibir("_diametro");
$valores['acueducto']=$validaciones->recibir("_acueducto");
$valores['alcantarillado']=$validaciones->recibir("_alcantarillado");
$valores['credito']=$validaciones->recibir("_credito");
$valores['certificado']=$validaciones->recibir("_certificado");
$valores['factura']=$validaciones->recibir("_factura");
$valores['conexion']=$validaciones->recibir("_conexion");
$valores['sexo']=$validaciones->recibir("_sexo");
$valores['nacimiento']=$validaciones->recibir("_nacimiento");
$valores['manzana']=$validaciones->recibir("_manzana");
$valores['seccion']=$validaciones->recibir("_seccion");
$valores['sector']=$validaciones->recibir("_sector");
$valores['ciudad']=$validaciones->recibir("_ciudad");
$valores['region']=$validaciones->recibir("_region");
$valores['pais']=$validaciones->recibir("_pais");
$valores['ciclo']=$validaciones->recibir("_ciclo");
$valores['ruta']=$validaciones->recibir("_ruta");
$valores['uso']=$validaciones->recibir("_uso");
$valores['habitaciones']=$validaciones->recibir("_habitaciones");
$valores['habitantes']=$validaciones->recibir("_habitantes");
/** Campos **/
$f->campos['solicitud'] = $f->text("solicitud", $valores['solicitud'], "10", "required primario", true);
$f->campos['suscriptor']=$f->text("suscriptor",$valores['suscriptor'],"10","required automatico",true);
$f->campos['documento']=$componentes->combo_documentos('documento', $valores['documento']);
$f->campos['identificacion']=$f->text("identificacion",$valores['identificacion'],"17","",false);
$f->campos['nombres']=$f->text("nombres",$valores['nombres'],"128","",false);
$f->campos['apellidos']=$f->text("apellidos",$valores['apellidos'],"128","",false);
$f->campos['direccion']=$f->text("direccion",$valores['direccion'],"128","",false);
$f->campos['referencia']=$f->text("referencia",$valores['referencia'],"128","",false);
$f->campos['estrato']=$estratos->combo("estrato", $valores['estrato']);
$f->campos['predial']=$f->text("predial",$valores['predial'],"30","",false);
$f->campos['latitud']=$f->text("latitud",$valores['latitud'],"30","",true);
$f->campos['longitud']=$f->text("longitud",$valores['longitud'],"30","",true);
$f->campos['correo']=$f->text("correo",$valores['correo'],"128","mail",false);
$f->campos['telefonos']=$f->text("telefonos",$valores['telefonos'],"128","",false);
$f->campos['creado']=$f->text("creado",$valores['creado'],"10","required automatico",true);
$f->campos['actualizado']=$f->text("actualizado",$valores['actualizado'],"10","",true);
$f->campos['creador']=$f->text("creador",$valores['creador'],"10","",true);
$f->campos['actualizador']=$f->text("actualizador",$valores['actualizador'],"10","",true);
$f->campos['diametro']=$tuberias->combo('diametro', $valores['diametro']);
$f->campos['acueducto']=$componentes->combo_sino("acueducto", $valores['acueducto']);
$f->campos['alcantarillado']=$componentes->combo_sino("alcantarillado", $valores['acueducto']);
$f->campos['credito']=$componentes->combo_tipo_credito("credito", $valores['credito']);
$f->campos['certificado']=$f->text("certificado",$valores['certificado'],"16","",true);
$f->campos['factura']=$f->text("factura",$valores['factura'],"16","",true);
$f->campos['conexion']=$componentes->combo_tipo_conexion("conexion", $valores['conexion']);
$f->campos['sexo']=$componentes->combo_sexo("sexo", $valores['sexo']);
$f->campos['nacimiento']=$f->text("nacimiento",$valores['nacimiento'],"10","",false);
$f->campos['manzana']=$f->text("manzana",$valores['manzana'],"2","",true);
$f->campos['seccion']=$f->text("seccion",$valores['seccion'],"2","",true);
$f->campos['sector']=$f->text("sector",$valores['sector'],"2","",true);
$f->campos['ciudad']=$f->text("ciudad",$valores['ciudad'],"5","",true);
$f->campos['region']=$f->text("region",$valores['region'],"3","",true);
$f->campos['pais']=$f->text("pais",$valores['pais'],"2","",true);
$f->campos['ciclo']=$f->text("ciclo",$valores['ciclo'],"1","",true);
$f->campos['ruta']=$f->text("ruta",$valores['ruta'],"4","",true);
$f->campos['uso']=$f->text("uso",$valores['uso'],"2","",true);
$f->campos['habitaciones']=$f->text("habitaciones",$valores['habitaciones'],"3","",true);
$f->campos['habitantes']=$f->text("habitantes",$valores['habitantes'],"3","",true);
$f->campos['ayuda']=$f->button("ayuda".$f->id, "button","Ayuda");
$f->campos['cancelar']=$f->button("cancelar".$f->id, "button","Cancelar");
$f->campos['continuar']=$f->button("continuar".$f->id, "submit","Continuar");
/** Celdas **/
$f->celdas["solicitud"] = $f->celda("Solicitud:", $f->campos['solicitud'], "csolicitud", "w100px");
$f->celdas["suscriptor"]=$f->celda("Suscriptor:",$f->campos['suscriptor'],"","w100px");
$f->celdas["documento"]=$f->celda("Documento:",$f->campos['documento']);
$f->celdas["identificacion"]=$f->celda("Identificacion:",$f->campos['identificacion']);
$f->celdas["nombres"]=$f->celda("Nombres:",$f->campos['nombres']);
$f->celdas["apellidos"]=$f->celda("Apellidos:",$f->campos['apellidos']);
$f->celdas["direccion"]=$f->celda("Dirección de Predio:",$f->campos['direccion']);
$f->celdas["referencia"]=$f->celda("Referencia:",$f->campos['referencia']);
$f->celdas["estrato"]=$f->celda("Estrato:",$f->campos['estrato']);
$f->celdas["predial"]=$f->celda("Predial:",$f->campos['predial']);
$f->celdas["latitud"]=$f->celda("Latitud:",$f->campos['latitud']);
$f->celdas["longitud"]=$f->celda("Longitud:",$f->campos['longitud']);
$f->celdas["correo"]=$f->celda("Correo Electrónico:",$f->campos['correo']);
$f->celdas["telefonos"]=$f->celda("Telefonos:",$f->campos['telefonos']);
$f->celdas["creado"]=$f->celda("Creado:",$f->campos['creado'],"","w100px");
$f->celdas["actualizado"]=$f->celda("Actualizado:",$f->campos['actualizado']);
$f->celdas["creador"]=$f->celda("Creador:",$f->campos['creador']);
$f->celdas["actualizador"]=$f->celda("Actualizador:",$f->campos['actualizador']);
$f->celdas["diametro"]=$f->celda("Diametro:",$f->campos['diametro']);
$f->celdas["acueducto"]=$f->celda("Acueducto:",$f->campos['acueducto']);
$f->celdas["alcantarillado"]=$f->celda("Alcantarillado:",$f->campos['alcantarillado']);
$f->celdas["credito"]=$f->celda("Credito:",$f->campos['credito']);
$f->celdas["certificado"]=$f->celda("Certificado:",$f->campos['certificado']);
$f->celdas["factura"]=$f->celda("Factura:",$f->campos['factura']);
$f->celdas["conexion"]=$f->celda("Conexion:",$f->campos['conexion']);
$f->celdas["sexo"]=$f->celda("Sexo:",$f->campos['sexo']);
$f->celdas["nacimiento"]=$f->celda("Fecha de Nacimiento:",$f->campos['nacimiento']);
$f->celdas["manzana"]=$f->celda("Manzana:",$f->campos['manzana']);
$f->celdas["seccion"]=$f->celda("Seccion:",$f->campos['seccion']);
$f->celdas["sector"]=$f->celda("Sector:",$f->campos['sector']);
$f->celdas["ciudad"]=$f->celda("Ciudad:",$f->campos['ciudad']);
$f->celdas["region"]=$f->celda("Region:",$f->campos['region']);
$f->celdas["pais"]=$f->celda("Pais:",$f->campos['pais']);
$f->celdas["ciclo"]=$f->celda("Ciclo:",$f->campos['ciclo']);
$f->celdas["ruta"]=$f->celda("Ruta:",$f->campos['ruta']);
$f->celdas["uso"]=$f->celda("Uso:",$f->campos['uso']);
$f->celdas["habitaciones"]=$f->celda("Habitaciones:",$f->campos['habitaciones']);
$f->celdas["habitantes"]=$f->celda("Habitantes:",$f->campos['habitantes']);
/** Filas **/
//$f->fila["fila1"]=$f->fila($f->celdas["suscriptor"].$f->celdas["documento"].$f->celdas["identificacion"].$f->celdas["nombres"]);
//$f->fila["fila2"]=$f->fila($f->celdas["apellidos"].$f->celdas["direccion"].$f->celdas["referencia"].$f->celdas["estrato"]);
//$f->fila["fila3"]=$f->fila($f->celdas["predial"].$f->celdas["latitud"].$f->celdas["longitud"].$f->celdas["correo"]);
//$f->fila["fila4"]=$f->fila($f->celdas["telefonos"].$f->celdas["creado"].$f->celdas["actualizado"].$f->celdas["creador"]);
//$f->fila["fila5"]=$f->fila($f->celdas["actualizador"].$f->celdas["diametro"].$f->celdas["acueducto"].$f->celdas["alcantarillado"]);
//$f->fila["fila6"]=$f->fila($f->celdas["credito"].$f->celdas["certificado"].$f->celdas["factura"].$f->celdas["conexion"]);
//$f->fila["fila7"]=$f->fila($f->celdas["sexo"].$f->celdas["nacimiento"].$f->celdas["manzana"].$f->celdas["seccion"]);
//$f->fila["fila8"]=$f->fila($f->celdas["sector"].$f->celdas["ciudad"].$f->celdas["region"].$f->celdas["pais"]);
//$f->fila["fila9"]=$f->fila($f->celdas["ciclo"].$f->celdas["ruta"].$f->celdas["uso"].$f->celdas["habitaciones"]);
//$f->fila["fila10"]=$f->fila($f->celdas["habitantes"]);
$f->fila["fila1"] = $f->fila("<h2>1. Solicitud & Matricula:</h2>");
$f->fila["fila2"] = $f->fila($f->celdas["solicitud"] . $f->celdas["suscriptor"] . $f->celdas["creado"] . $f->celdas["predial"] . $f->celdas["estrato"]);
$f->fila["fila3"] = $f->fila("<h2>2. Perfil del Suscriptor:</h2>");
$f->fila["fila4"] = $f->fila($f->celdas["documento"] . $f->celdas["identificacion"] . $f->celdas["nombres"] . $f->celdas["apellidos"] . $f->celdas["sexo"].$f->celdas["nacimiento"]);
$f->fila["fila5"] = $f->fila("<h2>3. Localización del Predio o Inmueble:</h2>");
$f->fila["fila6"] = $f->fila($f->celdas["direccion"] . $f->celdas["referencia"] . $f->celdas["telefonos"] . $f->celdas["correo"]);
$f->fila["fila7"] = $f->fila("<h2>4. Servicios & Financiación</h2>");
$f->fila["fila8"] = $f->fila($f->celdas["acueducto"] . $f->celdas["alcantarillado"] . $f->celdas["diametro"] . $f->celdas["conexion"] . $f->celdas["credito"]);

/** Compilando **/
$f->filas($f->fila['fila1']);
$f->filas($f->fila['fila2']);
$f->filas($f->fila['fila3']);
$f->filas($f->fila['fila4']);
$f->filas($f->fila['fila5']);
$f->filas($f->fila['fila6']);
$f->filas($f->fila['fila7']);
$f->filas($f->fila['fila8']);
//$f->filas($f->fila['fila9']);
//$f->filas($f->fila['fila10']);
/** Botones **/
$f->botones($f->campos['ayuda'], "inferior-izquierda");
$f->botones($f->campos['cancelar'], "inferior-derecha");
$f->botones($f->campos['continuar'], "inferior-derecha");
/** JavaScripts **/
$f->JavaScript("MUI.titleWindow($('".($f->ventana)."'),\"Matricula v3.0 201410150724\");");
$f->JavaScript("MUI.resizeWindow($('".($f->ventana)."'),{width: 800,height:400});");
$f->JavaScript("MUI.centerWindow($('".$f->ventana."'));");$f->eClick("cancelar".$f->id,"MUI.closeWindow($('".$f->ventana."'));");

?>